### ISSUE TITLE
Disabling selected options in multiselect

### ISSUE THREAD

**Issue by rouilj** [chalda-pnuzig/SimpleSearchableSelect#2]
When I use SimpleSearchableSelect with a multiselect, I can still select items in the list that have been selected.

When that happens, the item is swallowed and the list of inputs doesn't grow. This makes it look
like something failed.

Have you considered:

1) removing already selected items from the dropdown/search
2) disabling already selected items from the dropdown/search
3) adding a message just below the input saying something like "Your choice was already selected".

3 might be an issue as it raises the issue of localization of the message.

I am split on #1 and 2. Removing selected items would reduce the size of the dropdown (potentially) increasing the efficiency of selecting a new item. However, it might be confusing to the user who doesn't realize that his selection is already present and expects to find it in the dropdown

Option #2 seems to be the better choice as the user will find his/her item but the disabled formatting will provide a clue that it is already selected.

Thoughts?

**Comment by chalda-pnuzig** [comment]
At the moment, if the option is already present in the list, the option is selected and focus is applied to it.

Nevertheless, the suggestion to remove or disable the already selected option is good. 
Both options 1 and 2 are comparable, especially since applying the disabled attribute to an option in the datalist, as far as I know, effectively achieves the equivalent of hiding it.

Another alternative could be: 

- add to the text the strikethrough unicode combining character (e.g., "s̵e̵l̵e̵c̵t̵e̵d̵ ̵o̵p̵t̵i̵o̵n̵", see https://en.wikipedia.org/wiki/Strikethrough#Unicode )
- change the text to the bold/italic version ( e.g. "𝒔𝒆𝒍𝒆𝒄𝒕𝒆𝒅 𝒐𝒑𝒕𝒊𝒐𝒏" https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols, which however can only be applied to standard Latin letters) .
- add a symbol before text, e.g. "▶ selected option" (the easiest and least problematic one IMHO)

The option would remain visible and provide a clear visual reference that it has already been selected. 
However, I need to verify how this behaves on various devices and languages.

**Comment by rouilj** [comment]
>At the moment, if the option is already present in the list, the option is selected
>and focus is applied to it.

Hmm, I am not seeing that on the demo site. When I type I just get a plain list.
Nothing is highlighted. This is with firefox and chrome. The hidden underlying
select does have the item(s) selected.

<img width="270" alt="2023-12-07 08_31_26-SimpleSearchableSelect — Mozilla Firefox" src="https://github.com/chalda-pnuzig/SimpleSearchableSelect/assets/3751752/b32e4c98-9b23-48f3-9b29-84546852d729">

> Both options 1 and 2 are comparable, especially since applying the disabled attribute to
> an option in the datalist, as far as I know, effectively achieves the equivalent of hiding it.

Yes, that does seem to be the case.

I tried setting the font style for the datalist option via css which didn't work. Using
replacement unicode letters is an interesting idea. I agree it would be problematic and also
actually reading/rewriting the option list seems inefficient compared to adding/removing a
disabled attribute.

**Comment by chalda-pnuzig** [comment]
I introduce a new feature called `selectedStyle` in version 1.2.0. 
This option allows you to customize the styling and behavior of selected options according to your preferences.

Additionally, by default, selected options are now removed from datalist. 

I have added some usage examples to the demo.
